### ISSUE TITLE
线上版本已无法访问

### ISSUE THREAD

**Issue by dly023** [qixiaoo/QiuReader#26]
```
404
There isn't a GitHub Pages site here.

If you're trying to publish one, read the full documentation to learn how to set up GitHub Pages for your repository, organization, or user account.

GitHub Status — @githubstatus
```
chrome用户完全没办法使用这个阅读器了！

**Comment by qixiaoo** [comment]
@Engiun  抱歉，更改用户名之后 Github Pages 链接发生了变化，新链接：https://qixiaoo.github.io/QiuReader/

**Comment by qixiaoo** [comment]
由于域名发生了变化，使用数据还留在原来的域名下的浏览器存储中，访问新页面可能会发现书签消失了...

**Comment by dly023** [comment]
> @Engiun 抱歉，更改用户名之后 Github Pages 链接发生了变化，新链接：https://qixiaoo.github.io/QiuReader/

又可以了，感谢~
